# 45장. 프로미스

프로미스는 ES6에서 등장한 **비동기 처리**를 위한 패턴입니다.
기존 기술의 어떤 점을 개선하기 위해서 등장했을까요?

자바스크립트는 ES6 이전까지 **`콜백 함수`** 를 이용해서 비동기 처리를 해왔었는데요,
**콜백 헬**로 인해서 가독성이 좋지 않았고 **에러 처리**나 **여러 개의 비동기**를 한 번에 처리하는 것이 어려운 문제가 있습니다.

과연 이러한 점들을 프로미스가 어떻게 개선하였는지 함께 알아보도록 하겠습니다!

## 1. 비동기 처리를 위한 콜백 패턴의 단점

### 1-1. 콜백 헬

지금부터 get이라는 비동기 함수의 동작을 살펴보겠습니다.

```js
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 1. 서버의 응답을 반환
      return JSON.parse(xhr.response);
    }
    console.error(`${xhr.status} ${xhr.statusText}`);
  };
};

const response = get(`https://todo.com`);
console.log(response); // 2. undefined
```

먼저 이상한 점이 있다면 👀
`response` 값이 의도했던 대로 1번의 서버의 응답값을 나타내는 것이 아니라 `undefined`로 출력됩니다.

그 이유는 비동기 함수는 호출되면 **내부의 비동기 코드가 완료될 때까지 기다리지 않고 즉시 종료**되기 때문입니다.

따라서 onload라는 **비동기 이벤트 핸들러는 get이라는 비동기 함수가 종료된 이후에 실행**됩니다. 1번 코드가 실행되지 않았기 때문에 get 함수는 반환문이 없어서 undefined를 반환하였습니다.

그렇다면 서버의 응답을 상위 스코프의 변수에 할당하면 의도한대로 동작하게 될까요?

<br />

#### 응답을 상위 스코프 변수에 할당

```js
let todos;

const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 1. 서버의 응답을 반환
      todos = JSON.parse(xhr.response);
    }
    console.error(`${xhr.status} ${xhr.statusText}`);
  };
};

get(`https://todo.com`);
console.log(todos); // 2. undefined
```

이 또한 기대한 것처럼 동작하지 않습니다.
onload에 바인딩된 이벤트 핸들러는 언제나 2번의 console.log가 종료된 이후에 호출되기 때문입니다.

<br />

#### 실행 컨텍스트와 이벤트 루프

왜 순서가 보장되지 않는 걸까요?
실행 컨텍스트와 이벤트 루프와 연관지어 이해해보겠습니다.

1. 비동기 함수 get 호출
   - get 함수의 실행 컨텍스트 생성
   - 콜 스택에 Push
2. get 함수 코드 실행
   - xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러 바인딩
3. get 함수 종료
   - get 함수의 실행 컨텍스트가 콜 스택에서 Pop
4. console.log 호출
   - console.log의 실행 컨텍스트 생성
   - 콜 스택에 Push
5. 서버로부터 응답
   - xhr 객체에서 load 이벤트 발생
   - xhr.onload 이벤트 핸들러가 **태스크 큐에 저장**되어 대기
   - 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 Push, 실행
   - **콜 스택이 비어야 실행되므로 4번의 console.log가 이미 종료된 후에 실행되는 것**

<br />

#### 비동기 함수의 문제

위의 예제로부터 알게된 비동기 함수의 문제는 다음과 같습니다.

- 비동기 처리 결과를 외부에 반환할 수 없다.
- 상위 스코프의 변수에 할당할 수도 없다.

따라서 비동기 함수의 **후속 처리는 비동기 함수 내부에서 수행**해야 합니다.
이 때 우리는 비동기가 성공하면 호출될 콜백 함수와 실패하면 호출될 콜백 함수를 전달할 수 있습니다.

하지만 만약 후속 처리를 하는 비동기 함수가 또 다시 비동기 함수를 호출해야 한다면 함수의 복잡도가 높아질 것입니다. 이를 **`콜백 헬`** 이라고 합니다.

```js
get(`${url}/posts/1`, ({ userId }) => {
  console.log(userId);
  // userId를 이용해서 user 정보를 취득
  get(`${url}/users/${userId}`, (userInfo) => {
    console.log(userInfo);
  });
});
```

<br />

### 1-2. 에러 처리의 한계

콜백 패턴의 문제 중 가장 심각한 것은 에러 처리가 어렵다는 것입니다.

```js
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못합니다.
  console.log(e);
}
```

비동기 함수인 setTimeout의 콜백 함수에서 1초 뒤에 에러를 발생시킵니다. 하지만 이 에러는 catch 블록에서 캐치되지 않습니다.

왜 그럴까요..? 🤷‍♀️ 👀
다시 실행 컨텍스트와 연관지어 이해해보겠습니다.

#### 1. setTimeout 호출

- setTimeout의 실행 컨텍스트 생성
- 콜 스택에 Push
- 실행
- 콜 스택에서 Pop

#### 2. 타이머 만료

- 콜백 함수는 태스크 큐로 Push
- 이벤트 루프에 의해 콜 스택이 비었을 때 콜 스택으로 Push, 실행

<br />

콜백 함수가 실행될 때 setTimeout은 이미 제거된 상태입니다. 이것은 콜백 함수를 실행한 것이 setTimeout 함수가 아니라는 것을 의미합니다.

**에러는 호출자(Caller) 방향으로 전파**됩니다. 따라서, **콜백 함수의 호출자가 setTimeout이 아니기 때문**에 콜백 함수가 발생시킨 에러가 catch 블록에서 캐치되지 않았던 것입니다.

앞서 살펴본 `콜백 헬`과 `에러 처리`의 문제를 해결하기 위해 ES6에 `프로미스가 도입`되었습니다.

<br />

## 2. 프로미스의 생성

Promise 생성자 함수를 new 연산자와 함께 호출하면 Promise 객체를 생성합니다.

Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데, 이 콜백 함수는 resolve와 reject를 인수로 전달 받습니다.

```js
const promise = new Promise((resolve, reject)=>{
    if(/* 비동기 처리 성공 */){
        resolve('result');
    }else{ /* 비동기 처리 실패 */
        reject('failure reason')
    }
})
```

비동기 처리가 성공하면 resolve 함수를, 실패하면 reject 함수를 호출합니다.

앞서 살펴본 비동기 함수 get을 프로미스를 이용하여 다시 구현해보겠습니다!

<br />

#### 비동기 함수를 Promise로 구현

```js
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공
        resolve(JSON.parse(xhr.response));
      } else {
        // 실패
        reject(new Error(xhr.status));
      }
    };
  });
};

// 프로미스를 반환
promiseGet(`https://todo.com`);
```

비동기 처리는 Promise 생성자 함수가 인수로 받은 콜백 함수 내부에서 수행됩니다.

<br />

#### Promise의 비동기 처리 상태

생성된 직후의 프로미스는 기본적으로 **`pending`** 상태이고, 이후 성공 시에는 resolve 함수를 호출하여 **`fulfilled`** 상태로 변하며 실패에는 reject 함수를 호출하여 **`rejected`** 상태로 변경됩니다.

이 때, 비동기 처리가 수행된 fulfilled나 rejected 상태를 settled 상태라고 부릅니다. settled 상태가 되면 더는 다른 상태로 변할 수 없습니다.

<br />

#### Promise의 비동기 처리 결과

프로미스는 처리 상태 뿐만 아니라 결과 값도 상태로 가집니다.

```js
const fulfilled = new Promsie((resolve) => resolve(1));

// [[PromiseStatus]]: "fulfilled"
// [[PromiseValue]]: 1
```

즉, 프로미스는 **`비동기 처리 상태`** 와 **`처리 결과`** 를 관리하는 객체입니다.

<br />

## 3. 프로미스의 후속 처리 메서드

프로미스의 처리 상태가 변화하면 상태에 따라 처리를 해주어야 합니다. 이를 위해 프로미스는 후속 메서드 then, catch, finally를 제공합니다.

### 3-1. Promise.prototype.then

첫 번째 콜백 함수는 fulfilled 상태가 되면 호출됩니다. 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달 받습니다.

```js
new Promise((resolve) => resolve("fulfilled")).then(
  (v) => console.log(v), // fulfilled
  (e) => console.error(e)
);
```

두 번째 콜백 함수는 rejected 상태가 되면 호출됩니다. 콜백 함수는 프로미스의 에러를 인수로 전달 받습니다.

```js
new Promise((_, reject) => reject(new Error("rejected"))).then(
  (v) => console.log(v),
  (e) => console.error(e) // Error: rejected
);
```

<br />

### 3-2. Promise.prototype.catch

catch 메서드는 한 개의 콜백 함수를 인수로 전달 받습니다.
프로미스가 **rejected 상태인 경우에만 호출**됩니다.

```js
new Promise((_, reject) => reject(new Error("rejected"))).catch(
  (e) => console.error(e) // Error: rejected
);
```

<br />

### 3-3. Promise.prototype.finally

finally 메서드는 한 개의 콜백 함수를 인수로 전달 받으며 프로미스의 성공 실패 여부와는 상관없이 **무조건 한 번 호출**됩니다.
then/catch 메서드와 마찬가지로 언제나 프로미스를 반환합니다.

```js
new Promise(() => {}).finally(() => console.log("finally")); //finally
```

앞서 살펴봤던 promiseGet 함수의 후속처리를 구현해보겠습니다.

```js
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        // 성공
        resolve(JSON.parse(xhr.response));
      } else {
        // 실패
        reject(new Error(xhr.status));
      }
    };
  });
};

// 프로미스를 반환
promiseGet(`https://todo.com`)
  .then((res) => console.log(res))
  .catch((err) => console.error(err))
  .finally(() => console.log("Bye!"));
```

<br />

## 4. 프로미스의 에러 처리

콜백 패턴을 사용하게 되면 에러 처리가 어렵다는 문제가 있었습니다.
그렇다면 프로미스에서는 이러한 점을 어떻게 개선했을까요?

#### then

먼저, 프로미스에서는 then의 두 번째 콜백 함수로 처리할 수 있습니다.

```js
const wrongUrl = "https://wrong.com";

promiseGet(wrongUrl).then(
  (res) => console.log(res),
  (err) => console.error(err)
); // Error: 404
```

#### catch

하지만, then 메서드의 두 번째 콜백 함수에서는 **첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하는 문제**가 있습니다.

따라서 **모든 then 메서드를 호출한 이후에 catch 메서드를 호출**하여, 비동기 처리에서 발생한 에러 뿐만 아니라 then 메서드 내부에서 발생한 에러까지 **한 번에 캐치**하는 방식이 권장됩니다.

```js
const wrongUrl = "https://wrong.com";

promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .catch((err) => console.error(err)); // TypeError: console.xxx is not a function
```

<br />

## 5. 프로미스 체이닝

이제 프로미스가 콜백 패턴의 에러 처리 문제를 어떻게 개선했는지 알게 되었습니다!

그렇다면 콜백 헬 문제는 어떻게 개선하였을까요?
프로미스는 then, catch, finally 후속 처리 메서드를 이용해서 콜백 헬을 해결했습니다.

앞서 콜백 헬이 발생했던 예제를 프로미스를 이용해서 다시 구현해보겠습니다.

#### 콜백 헬 예제

```js
get(`${url}/posts/1`, ({ userId }) => {
  console.log(userId);
  // userId를 이용해서 user 정보를 취득
  get(`${url}/users/${userId}`, (userInfo) => {
    console.log(userInfo);
  });
});
```

<br />

#### 프로미스로 개선

```js
promiseGet(`${url}/posts/1`)
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
```

then, catch, finally 후속 처리 메서드는 언제나 프로미스를 반환하기 때문에 연속적으로 호출할 수 있습니다.

이를 프로미스 체이닝이라고 합니다.

정리하자면, 프로미스는 **프로미스 체이닝을 통해 비동기 처리에 대한 후속 처리**를 하므로 **콜백 헬이 발생하지 않습니다.**

하지만 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아닙니다.
따라서 **콜백 함수로 인한 가독성 문제를 해결**하기 위해서 ES8에서는 **async/await**이 등장했습니다.
async/await을 이용하면 후속 처리 메서드 없이도 마치 **동기적으로 동작하는 것처럼** 프로미스 처리 결과를 반환하도록 구현할 수 있게 됩니다.

<br />

#### async/await 맛보기

```js
(async () => {
  const { userId } = await promiseGet(`${url}/posts/1`);

  const userInfo = await promiseGet(`${url}/users/${userId}`);

  console.log(userInfo);
})();
```

<br />

## 6. 프로미스의 정적 메서드

프로미스는 주로 생성자 함수로 사용되지만, 함수도 객체이기 때문에 메서드를 가질 수 있습니다.
프로미스는 총 5가지 정적 메서드를 제공합니다.

### 6-1. Promise.resolve / Promise.reject

이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용됩니다.

```js
// 배열을 resolve하는 프로미스 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1,2,3]
```

아래의 예제와 동일하게 동작합니다.

```js
const resolvedPromise = new Promise((resolve) => resolve([1, 2, 3]));
resolvedPromise.then(console.log); // [1,2,3]
```

<br />

### 6-2. Promise.all

여러 개의 비동기 처리를 모두 병렬 처리할 때 사용됩니다.

```js
const request1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const request2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const request3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 병렬로 처리
Promise.all([request1(), request2(), request3()])
  .then(console.log) // [1, 2, 3] => 약 3초 소요
  .catch(console.error);
```

전달받은 **모든 프로미스가 fulfilled 상태가 되면** 모든 처리 결과를 배열에 저장하여 새로운 프로미스를 반환합니다.

따라서 메서드가 종료되는데 걸리는 시간은 가장 늦게 fulfilled 상태가 되는 프로미스의 처리 시간보다 조금 더 깁니다. 위 예제에서는 가장 긴 처리 시간인 3초보다 조금 더 소요될 것입니다.

특이한 점은, **처리 순서가 보장된다**는 점입니다. request3 함수가 가장 먼저 처리 완료 되었어도 첫 번째 프로미스 결과부터 차례대로 배열에 저장하여 반환합니다.

<br />

#### 하나라도 reject 된다면?

배열의 프로미스가 **하나라도 rejected 상태**가 된다면 나머지 프로미스 결과를 기다리지 않고 **즉시 종료**합니다.

```js
Promise.all([
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 1")), 3000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 2")), 2000)
  ),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error 3")), 1000)
  ),
])
  .then(console.log)
  .catch(console.log); // Error: Error 3
```

위의 예제의 경우 마지막 프로미스가 가장 먼저 rejected 상태가 되므로 catch 메서드에서 3이 출력된 것을 확인할 수 있습니다.

<br />

### 6-3. Promise.race

Promise.all 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받습니다.

다른 점이 있다면, **가장 먼저 fulfilled 상태가 된 프로미스의 결과를 resolve**하는 새로운 프로미스를 반환합니다.

```js
const request1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const request2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const request3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.race([request1(), request2(), request3()])
  .then(console.log) // 3
  .catch(console.error);
```

가장 먼저 처리된 request3이 출력된 것을 볼 수 있습니다.
**reject의 경우 Promise.all과 마찬가지**로 하나라도 rejected 상태가 되면 에러를 reject하는 새로운 프로미스를 즉시 반환합니다.

<br />

### 6-4. Promise.allSettled

위의 메서드들과 마찬가지로 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받고,
전달받은 프로미스가 **모두 settled 상태가 되면 처리 결과를 배열로 반환**합니다.

```js
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error!")), 1000)
  ),
]).then(console.log);

/*
[
    {status: "fulfilled", value: 1},
    {status: "rejected", reason: Error: Error! at <anonymous>:3:54},
]
*/
```

- fulfilled인 경우: status 프로퍼티, 처리 결과를 나타내는 value 프로퍼티
- rejected인 경우: status 프로퍼티, 에러를 나타내는 reason 프로퍼티

<br />

## 7. 마이크로태스크 큐

다음 예제를 살펴보고 어떤 순서로 로그가 출력될지 생각해봅시다!

```js
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

정답은..!

```
2
3
1
```

그 이유는 프로미스의 콜백 함수는 마이크로태스크 큐에 저장되기 때문입니다. **마이크로태스크 큐는 태스크 큐보다 우선순위가 높습니다.**

이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐의 대기 함수를 실행하고 그 이후 태스크 큐에서 대기하고 있는 함수를 가져와 실행합니다.

태스크 큐에는 비동기 함수의 콜백 함수나 이벤트 핸들러가 저장됩니다.

<br />

## 8. fetch

fetch 함수는 HTTP 통신을 제공하는 클라이언트 사이드 Wep API 입니다.

XMLHttpRequest 객체보다 사용법이 간단하고 **프로미스를 지원**하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭습니다.

fetch 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, 요청 헤더, 페이로드 등을 설정한 객체를 전달합니다.

```js
const promise = fetch(url, [, options]);
```

그리고 fetch 함수는 HTTP 응답을 나타내는 **Response 객체를 래핑한 Promise 객체를 반환**합니다.

```js
fetch("/todos").then((response) => console.log(response));
```

json 메서드를 이용하면 Response 객체에서 HTTP 응답의 **body를 json 형태에서 객체 형태로 변환**할 수 있습니다.

```js
fetch("/todos")
  .then((response) => response.json())
  .then((json) => console.log(json)); // { userId: 1, id:1 }
```

<br />

#### fetch의 에러 처리

주의해야할 점은 fetch 함수가 반환하는 프로미스는 404나 500과 같은 **HTTP 에러가 발생해도 에러를 reject하지 않습니다.** 네트워크 장애나 CORS 에러와 같은 경우에만 reject를 반환합니다.

대신, HTTP 에러의 경우 불리언 타입의 ok 상태를 false로 설정한 객체를 resolve하기 때문에, **ok 상태를 통해 명시적으로 에러를 처리해주는 것이 필요**합니다!

```js
fetch(wrongUrl).then((response) => {
  if (!response.ok) throw new Error(response.statusText);
  return response.json();
});
```

<br />

#### axios는 fetch의 어떤 점을 개선했을까요?

axios는 fetch와 달리 **모든 HTTP 에러를 reject** 하는 프로미스를 반환하기 때문에 **모든 에러를 catch에서 처리**할 수 있어서 에러 처리가 보다 편리해졌습니다.
