# 45장 - 프로미스
자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용했습니다. 콜백 패턴은 조금만 연속되어도 가독성이 나쁘고 비동기 처리 중 발생한 예외 처리가 곤란하며 여러개의 비동기 처리를 한번에 처리하는데 한계가 있었습니다.

이러한 단점들을 보완하고자 ES6에서는 또 다른 패턴인 `프로미스(Promise)`를 도입했습니다. **프로미스는 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있습니다.**

<br/>

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1 콜백 헬
```js
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if(xhr.status === 200) {
      // 서버의 응답을 콘솔에 출력합니다.
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 todos를 취득
get('https://jsonplaceholder.typicode.com/todos/1');

/*
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
*/
```
위 예제의 **get 함수는 비동기 함수**입니다. 비동기 함수란 함수 내부에 비동기로 동작하는 코드를 포함한 함수를 말합니다.

비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료됩니다. 즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료됩니다. 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않습니다.

<br/>

```js
let g = 0;

// 비동기 함수인 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하지 못합니다.
setTimeout(() => { g = 100 }, 0);
console.log(g); // 0
```
**setTimeout 함수는 비동기 함수**입니다.
`setTimeout` 함수를 호출하면 콜백 함수를 호출 스케줄링한 다음, 타이머 id를 반환하고 즉시 종료됩니다. 즉, 비동기 함수인 `setTimeout` 함수의 콜백 함수는 `setTimeout` 함수가 종료된 이후에 호출됩니다. 따라서 위 코드 처럼 `setTimeout` 함수 내부의 콜백 함수에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않습니다.

<br/>

```js
// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if(xhr.status === 200) {
      // 서버의 응답을 반환합니다.
      return JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 todos를 취득
const response = get('https://jsonplaceholder.typicode.com/todos/1');
console.log(response); // undefined
```
위 코드의 get 함수는 비동기 함수입니다. get 함수가 비동기 함수인 이유는 **get 함수 내부의 onload 이벤트 핸들러가 비동기로 동작하기 때문**입니다. get 함수를 호출하면 GET 요청을 전송하고 onload 이벤트 핸들러를 등록한 다음 undefined를 반환하고 즉시 종료합니다.

코드의 호출 과정을 살펴보도록 하겠습니다.
가장 먼저 get 함수가 호출되면 XMLHttpRequest 객체를 생성하고, HTTP 요청을 초기화한 후, HTTP 요청을 전송합니다. 그리고 xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러를 바인딩하고 종료합니다. (이때 get 함수의 명시적인 반환값이 없으므로 undefined를 반환합니다.)

<br/>

#### 그렇다면 상위 스코프의 변수에 서버의 응답을 할당하면 어떻게 될까요?
```js
let todos;

// GET 요청을 위한 비동기 함수
const get = url => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if(xhr.status === 200) {
      // 1. 서버의 응답을 상위 스코프의 변수에 할당합니다.
      todos = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// id가 1인 todos를 취득
get('https://jsonplaceholder.typicode.com/todos/1');
console.log(todos); // 2. undefined
```
이 또한 기대한 대로 동작하지 않습니다.

get 함수가 호출되면 함수 코드를 평가하는 과정에서 get 함수의 실행 컨텍스트가 생성되고 실행 컨텍스트 스택에 푸시됩니다. 이후 get 함수 실행 과정에서 비동기 함수인 xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩 됩니다.
get 함수가 종료되면 get 함수는 실행 컨텍스트에서 팝되고, 곧바로 console.log(todos)가 호출 됩니다. 이때 console.log의 실행 컨텍스트가 생성되어 실행 컨텍스트 스택에 푸시됩니다. 만약 console.log가 호출되기 직전에 load 이벤트가 발생되었더라도 xhr.onload 이벤트 핸들러는 결코 console.log보다 먼저 실행되지 않습니다.
서버로 응답이 도착하면 xhr객체에서 load 이벤트가 발생합니다. 이때 이벤트 핸들러가 즉시 실행되는 것이 아닙니다. load 이벤트가 발생하면 일단 태스크 큐에 저장되어 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행되어 집니다.

> 이벤트 핸들러도 함수이므로 이벤트 핸들러의 평가 -> 이벤트 핸들러의 실행 컨텍스트 생성 -> 콜 스택에 푸시 -> 이벤트 핸들러 실행 과정을 거치게 됩니다.

이처럼 **비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없습니다.** 따라서 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 합니다. 이때 사용할 수 있는 방법이 **`콜백 함수를 전달하는 것`** 입니다. 필요에 따라 **비동기 처리가 성공하면 호출될 콜백 함수와 비동기 처리가 실패하면 호출될 콜백 함수를 전달**할 수 있습니다.

<br/>

#### 비동기 함수에 콜백 함수(성공, 실패)를 전달하면 어떤 것이 달라지는 지 살펴보겠습니다. 
```js
// GET 요청을 위한 비동기 함수
const get = (url, successCallback, failureCallback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if(xhr.status === 200) {
      // 서버의 응답을 콜백 함수의 인자로 전달하면서 호출하여 응답에 대한 후속처리를 합니다.
      successCallback(JSON.parse(xhr.response));
    } else {
      // 에러 정보를 콜백 함수에 인수로 전달하면서 호출하여 에러 처리를 한다.
      failerCallback(xhr.status);
    }
  };
};

get('https://jsonplaceholder.typicode.com/todos/1', console.log, console.error);
/*
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
*/
```
이 처럼 콜백 함수를 사용하면 비동기 함수의 처리 결과에 대한 후속 처리를 진행할 수 있습니다.

하지만 이러한 콜백 함수 처리 방법에도 단점이 존재합니다. 만약 비동기 함수의 처리결과를 가지고 또 다시 비동기 함수를 호출해야 한다면 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생하게 됩니다.

이러한 문제를 **`콜백 헬(callback bell)`** 이라 합니다. 아래 예제를 통해 콜백 헬에 대해 살펴보도록 하겠습니다.
```js
// GET 요청을 위한 비동기 함수
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.onload = () => {
    if(xhr.status === 200) {
      // 서버의 응답을 콜백 함수의 인자로 전달하면서 호출하여 응답에 대한 후속처리를 합니다.
      callback(JSON.parse(xhr.response));
    } else {
      // 에러 정보를 콜백 함수에 인수로 전달하면서 호출하여 에러 처리를 한다.
      console.error(`${xhr.status}, ${xhr.statusText}`);
    }
  };
};

const url = 'https://jsonplaceholder.typicode.com';

// id가 1인 todos의 userId를 취득
get(`${url}/todos/1`, ({ userId }) => {
    console.log(userId); // 1

    // todos의 userId를 사용하여 user 정보를 취득
    get(`${url}/users/${userId}`, userInfo => {
        console.log(userInfo);
    });
});
```
위 예제를 보면 GET 요청을 통해 서버로부터 응답을 받고 이 데이터를 이용해 또 다시 GET 요청을 합니다. 콜백 헬은 가독성을 나쁘게 하며 실수를 유발하는 원이니 됩니다. 아래 코드는 콜백 헬이 발생하는 전형적인 사례입니다.
```js
get('/step1', a => {
  get('/step2', b => {
    get('/step3', c => {
      get('/step4', d => {
        console.log(d);
      });
    });
  });
});
```

<br/>

### 45.1.2 에러 처리의 한계
비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란하다는 것입니다.
```js
try {
  setTimeout(() => { throw new Error('Error!');, 1000});
} catch (e) {
  // 에러를 캐치하지 못합니다.
  console.log('캐치한 에러', e);
}
```
setTimeout 함수를 호출하면 1초 후에 에러를 발생하는 코드를 실행시켰습니다. 코드가 실행되면 에러가 발생하게 되고 에러가 발생하면 catch문에서 해당 에러를 콘솔에서 출력해줄 것이라고 생각했습니다.

#### 하지만 그렇게 동작하지 않습니다. 왜 그런걸까요?

그 이유는 `setTimeout` 함수가 비동기 함수이기 때문입니다. 해당 함수는 실행 즉시 실행 컨텍스트에서 `Web API`로 보내지고 `setTimeout` 함수는 콜 스택에서 제거됩니다. 이후 타이머가 완료되면 `setTimeout` 함수의 콜백 함수는 `태스크 큐`로 푸시됩니다. 이후 콜 스택이 비어졌을 때 콜백 함수는 이벤트 루프에 의해 콜 스택으로 푸시되어 실행됩니다.

이때 중요한 문제가 발생합니다. 콜백 함수가 실행될 시점에 **`setTimeout`은 이미 콜 스택에서 제거된 상태**입니다. 이말은 즉 **setTimeout의 콜백 함수를 호출한 것이 setTimeout이 아니라는 말** 입니다. **에러는 호출자 방향으로 전파됩니다.** 즉, 콜 스택의 아래 방향(실행중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파 됩니다. 하지만 콜백 함수를 호출한 것은 setTimeout이 아닙니다. 따라서 콜백 함수가 발생 시킨 에러는 catch 블록에서 캐치되지 않습니다.

지금까지 살펴본 비동기 처리를 위한 콜백 패턴은 콜백 헬, 에러 처리의 문제가 있습니다. 이를 해결하기 위해 ES6에서 **프로미스(Promise)가 도입**되었습니다.

<br/>

## 45.2 프로미스의 생성
`Promise` 생성자 함수를 new 연산자와 함께 호출하면 프로미스 객체를 생성합니다.

`Promise` 생성자 함수는 비동기 처리를 수행할 콜백 함수(ECMAScript 사양에서는 **executor 함수**라고 부릅니다.)를 인수로 전달 받는데 이 콜백 함수는 `resolve(성공)`와 `reject(실패)` 함수를 인수로 전달 받습니다.

```js
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행합니다.
  if(true) {
    // 비동기 처리 성공
    resolve('result');
  } else {
    // 비동기 처리 실패
    reject('failure reason');
  } 
});
```
`Promise` 함수가 인수로 전달받은 **콜백 함수 내부에서 비동기 처리를 수행**합니다. 이때 **비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 resolve 함수를 호출**하고, **비동기 처리가 실패하면 reject 함수를 호출**합니다.

<br/>

앞에서 살펴본 비동기 함수 get을 프로미스를 사용해 다시 구현해보겠습니다.
```js
// GET 요청을 위한 비동기 함수
const promiseGet = url => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.onload = () => {
      if(xhr.status === 200) {
        // 성공적으로 응답을 전달받으면 resolve 함수를 호출합니다.
        resolve(JSON.parse(xhr.response));
      } else {
        // 에러 처리를 위해 reject 함수를 호출합니다.
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환합니다.
promiseGet('https://jsonplaceholder.typicode.com/todos/1');
```
비동기 함수인 promiseGet은 함수 내부에서 프로미스를 생성하고 반환합니다. 비동기 처리는 `Promise` 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 수행합니다. 만약 비동기 처리가 성공하면 비동기 처리 결과를 resolve 함수에 인수로 전달하면서 호출되고, 실패하면 reject 함수에 인수로 전달하면서 호출됩니다.

<br/>

|프로미스의 상태|의미|상태 변경 조건|
|------|---|---|
|pending|비동기 처리가 아직 수행되지 않은 상태|프로미스가 생성된 직후 기본 상태|
|fullfilled|비동기 처리가 수행된 상태(성공)|resolve 함수 호출|
|rejected|비동기 처리가 수행된 상태(실패)|reject 함수 호출|

생성된 직후의 프로미스는 기본적으로 pending 상태 입니다. 이후 비동기 처리가 수행되면 비동기 처리 결과에 따라 다음과 같이 프로미스 상태가 변경됩니다.

<br/>

#### 비동기 처리 성공
resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경합니다.

#### 비동기 처리 실패
reject 함수를 호출해 프로미스를 rejected 상태로 변경합니다.

<br/>

이처럼 **프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정**됩니다.

<br/>

fulfilled 또는 rejected 상태를 settled 상태라고 합니다. settled 상태는 비동기 처리가 수행된 상태를 말합니다.

<br/>

```js
// fulfilled된 프로미스
const fulfilled = new Promise(resolve => resolve(1));
```
비동기 처리가 성공하면 프로미스는 pending 상태에서 fullfiled 상태로 변화합니다.

<br/>

```js
// rejected된 프로미스
const rejected = new Promise((_, reject) => reject(new Error('error occurred')));
```
비동기 처리가 실패하면 프로미스는 pending 상태에서 rejected 상태로 변화합니다.

<br/>

> **프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체입니다.**

<br/>

## 45.3 프로미스의 후속 처리 메서드
프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야 합니다. 프로미스는 then, catch, finally라는 후속 처리 메서드를 제공합니다.

프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출됩니다.
이때 후속 처리 메스드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달됩니다.

지금부터 후속 처리 메서드에 대해 알아보도록 하겠습니다.

### 45.3.1 Promise.prototype.then
`then 메서드`는 두 개의 콜백 함수를 인자로 전달 받습니다.
- **첫 번째 콜백 함수는 프로미스가 fulfilled(resolve 함수) 상태가 되면 호출**됩니다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달 받습니다.
- **두 번째 콜백 함수는 프로미스가 rejected(reject 함수) 상태가 되면 호출**됩니다. 이때 콜백 함수는 프로미스의 에러를 인수로 전달 받습니다.

<br/>

즉, 첫 번째 콜백 함수는 비동기 처리가 성공했을 때 호출되는 성공 처리 콜백 함수이며, 두 번째 콜백 함수는 비동기 처리가 실패했을 때 호출되는 실패 처리 콜백 함수 입니다.
```js
// fulfilled
new Promise(resolve => resolve('fulfilled'))
.then(v => console.log(v), e => console.log(e)); // fulfilled

// rejected
new Promise(reject => reject(new Error('rejected')))
.then(v => console.log(v), e => console.log(e)); // Error: rejected
```
then 메서드는 언제나 프로미스를 반환합니다. 만약 then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 콜백 함수가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject하여 프로미스를 생성해 반환한다.

<br/>

### 45.3.2 Promise.prototype.catch
`catch 메서드`는 한 개의 콜백 함수를 인수로 전달 받습니다. `catch 메서드`의 **콜백 함수는 프로미스가 rejected 상태인 경우만 호출**됩니다.
```js
// rejected
new Promise((_, reject) => reject(new Error('rejected')))
.catch(e => console.log(e)); // Error : rejected
```
catch 메서드는 then과 동일하게 동작합니다. then 메서드와 마찬가지로 언제나 프로미스를 반환합니다.

<br/>

### 45.3.3 Promise.prototype.finally
`finally 메서드`는 한개의 콜백 함수를 인수로 전달 받습니다. **finally 메서드의 콜백 함수는 프로미스의 성공(fulfilled) 또는 실패(rejected)와 상관없이 무조건 한 번 호출됩니다.**

finally 메서드는 프로미스 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용합니다.
```js
// finally
new Promise(()=> {})
.finally(() => console.log('finally')); // finally
```

<br/>

## 45.4 프로미스의 에러 처리
비동기 처리에서 발생한 에러는 then 메서드의 두 번째 콜백 함수와 프로미스 후속 처리 메서드 catch를 사용해 처리할 수 있습니다.
```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생합니다.
promiseGet(wrongUrl)
.then(res => console.log(res))
.catch(err => console.error(err)); // Error : 404
```
catch 메서드를 호출하면 내부적으로 then(undefined, onRejected)을 호출합니다. 위 예제는 내부적으로 다음과 같이 처리됩니다.
```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 지정되었기 때문에 에러가 발생합니다.
promiseGet(wrongUrl)
.then(res => console.log(res))
.then(undefined, err => console.error(err)); // Error : 404
```
단, then 메서드를 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고 코드가 복잡해져서 가독성이 좋지 않습니다.

이럴때 catch 메서드를 모든 then 메서드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러(rejected 상태)뿐만 아니라 then 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있습니다.
```js
promiseGet('https://jsonplaceholder.typicode.com/todos/1')
.then(res => console.xxx(res))
.catch(err => console.error(err)); // TypeError: console.xxx is not a function
```
또한 then 메서드에 두 번째 콜백 함수를 전달하는 것보다 catch 메서드를 사용하는 것이 가독성이 좋습니다.
따라서 promise에서 에러 처리는 catch 메서드를 사용하는 것을 권장합니다.

<br/>

## 45.5 프로미스 체이닝
프로미스 체이닝을 이용하면 앞서 살펴본 비동기 처리를 위한 콜백 패턴에서 발생하는 콜백 헬 문제를 해결할 수 있습니다.

콜백 헬이 발생하는 예제를 프로미스를 사용해서 다시 구현해보겠습니다.
```js
const url = 'https://jsonplaceholder.typicode.com';

// id가 1인 post의 userId를 취득
promiseGet(`${url}/posts/1`)
// 취득한 post의 userId로 user 정보를 취득
.then(({ userId }) => promiseGet(`${url}/users/${userId}`))
.then(userInfo => console.log(userInfo))
.catch(err => consol.error(err));
```
위 예제를 살펴보면 then -> then -> catch 순서로 후속 처리 메서드를 사용한 걸 볼 수 있습니다. **then, catch, finally 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있습니다. 이를 프로미스 체이닝(Promise chaining)이라고 합니다.**

프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백 헬이 발생하지 않습니다. 다만 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아닙니다.

콜백 패턴은 **가독성이 좋지 않기 때문에 이를 해결하기 위해 ES8에서 도입된 `async/await`를 사용하면 위 문제를 해결할 수 있습니다.** `async/await`를 사용하면 프로미스의 후속 처리 메서드 없이 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있습니다.

<br/>

## 45.6 프로미스의 정적 메서드
promise는 주로 생성자 함수로 사용되지만 함수도 객체이므로 메서드를 가질 수 있습니다.  Promise는 5가지 정적 메서드를 제공합니다.

### 45.6.1 Promise.resolve / Promise.reject
Promise.resolve와 Promise.reject 메서드는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용합니다.
Promise.resolve 메서드는 인수로 전달받은 값을 resolve하는 프로미스를 생성합니다.
```js
// 배열을 resolve하는 프로미스를 생성
const resolvePromise = Promise.resolve([1,2,3]);
resolvedPromise.then(console.log); // [1,2,3];
```
위 예제는 다음 예제와 동일하게 동작합니다.
```js
const resolvedPromise = new Promise(resolve => resolve([1,2,3)));
resolvedPromise.then(console.log); // [1, 2, 3]
```

<br/>

Promise.reject 메서드는 인수로 전달받은 값을 reject하는 프로미스를 생성합니다.
```js
// 에러 객체를 reject하는 프로미스를 생성
const rejectedPromise = Promise.reject(new Error('Error'));
rejectedPromise.catch(console.log); // Error: Error;
```
위 예제는 다음과 같이 동작합니다.
```
const rejectedPromise = new Promise((resolve, reject) => reject(new Error('Error')));
rejectedPromise.catch(console.log); // Error: Error;
```

<br/>

### 45.6.2 Promise.all
`Promise.all` 메서드는 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용됩니다. 아래 예제를 통해 살펴보겠습니다.
```js
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 순차적으로 처리
const res = [];
requestData1.then(data => {
  res.push(data);
  return requestData2;
}).then(data => {
  res.push(data);
  return requestData3;
}).then(data => {
  res.push(data);
  console.log(res); // [1, 2, 3] => 약 6초 소요
}).catch(console.error);
```
위 예제는 세 개의 비동기 처리를 순차적으로 처리합니다. 하지만 세 개의 비동기 처리는 서로 의존하지 않고 개별적으로 수행됩니다. 즉, 앞선 비동기 처리 결과를 다음 비동기 처리가 사용하지 않습니다. 따라서 위 예제의 경우 비동기 처리를 순차적으로 처리할 필요가 없습니다.

<br/>

`Promise.all` 메서드는 여러개의 비동기 처리를 모두 병렬 처리할 때 사용한다고 했습니다. `Promise.all`을 사용해 세 개의 비동기 처리를 병렬로 처리해보겠습니다.
```js
const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 병렬로 처리
Promise.all([requestData1(), requestData2(), requestData3()])
.then(console.log); // [1, 2, 3] => 약 3초 소요
.catch(console.error);
```
`Promise.all` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받습니다. 그리고 전달받은 모든 프로미스가 모두 fulfilled 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환합니다.

위 예제는 다음과 같이 동작합니다.
- 첫 번째 프로미스는 3초 후에 1을 resolve 합니다.
- 두 번째 프로미스는 2초 후에 2을 resolve 합니다.
- 세 번째 프로미스는 1초 후에 3을 resolve 합니다.

<br/>

`Promise.all` 메서드는 인수로 전달받은 배열의 모든 프로미스가 모두 fulfilled 상태가 되면 종료합니다.

위 예제의 경우 모든 처리에 걸리는 시간은 가장 늦게 fulfilled 상태가 되는 첫 번째 프로미스의 처리 시간인 3초보다 조금 더 소요됩니다.

첫 번째 프로미스가 가장 나중에 fulfilled 상태가 되어도 `Promise.all` 메서드는 첫 번째 프로미스가 resolve한 처리 결과부터 차례대로 배열에 저장해 그 배열을 resolve하는 새로운 프로미스를 반환합니다.(즉, 처리 순서가 보장됩니다.)

<br/>

**Promise.all 메서드는 인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고 즉시 종료합니다.**
```js
Promise.all([
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 3000)),
  new Promise((resolve, reject) => setTimeout(() => resolve(2), 2000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 3')), 1000))
])
.then(console.log)
.catch(console.log); // Error : Error 3
```

<br/>

**Promise.all 메서드는 인수로 전달받은 이터러블의 요소가 프로미스가 아닌 경우 Promise.resolve 메서드를 통해 프로미스로 래핑합니다.**
```js
Promise.all([
  1, // -> Promise.resolve(1);
  2, // -> Promise.resolve(2);
  3  // -> Promise.resolve(3);
])
.then(console.log) // [1, 2, 3]
.catch(console.log)
```

<br/>

### Promise.race
`Promise.race` 메서드는 `Promise.all` 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받습니다. `Promise.ract`는 `Promise.all` 처럼 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 것이 아니라 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 반환합니다.
```js
Promise.race([
  new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
  new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
  new Promise(resolve => setTimeout(() => resolve(3), 1000)) // 3
])
.then(console.log) // 3
.catch(console.log)
```
프로미스가 하나라도 rejected 상태가 되면 에러를 reject하는 새로운 프로미스를 즉시 반환합니다.

<br/>

### Promise.allSettled
`Promise.allSettled` 메서드는 프로미스 요소를 갖는 배열 등의 이터러블을 인수로 전달 받습니다. **전달 받은 프로미스가 모두 settled 상태(비동기 처리가 수행된 상태 fulfilled, rejected)가 되면 처리 결과를 배열로 변환합니다.**

ES11(ECMAScript 2020)에 도입된 `Promise.allSettled` 메서드는 IE를 제외한 대부분의 모던 브라우저에서 지원합니다.
```js
Promise.allSettled([
  new Promise(resolve => setTimeout(() => resolve(1), 2000)),
  new Promise((_, rejected) => setTimeout(() => reject(new Error('Error'), 1000)))
])
.then(console.log);
/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at ...},
]
*/
```
`Promise.allSettled` 메서드가 반환한 배열에는 fulfilled 또는 rejected 상태와는 상관없이 `Promise.allSettled` 메서드가 인수로 전달 받은 모든 프로미스들의 처리 결과가 담겨 있습니다. 프로미스의 처리 결과를 나타내는 객체는 다음과 같습니다.

- 프로미스가 fulfilled 상태인 경우 비동기 처리 상태를 나타내는 `status` 프로퍼티와 처리 결과를 나타내는 `value` 프로퍼티를 갖습니다.
- 프로미스가 rejected 상태인 경우 비동기 처리 상태를 나타내는 `status` 프로퍼티와 에러를 나타내는 `reason` 프로퍼티를 갖습니다.

<br/>

## 45.7 마이크로태스크 큐
다음 예제를 살펴보고 어떤 순서로 로그가 출력될 지 생각해봅시다.
```js
setTimeout(() => console.log(1), 0);

Promise.resolve()
.then(() => console.log(2))
.then(() => console.log(3));
```
프로미스 후속 처리 메서드도 비동기로 동작하므로 1 -> 2 -> 3으로 출력될 것처럼 보이지만 2 -> 3 -> 1의 순으로 출력됩니다. 그 이유는 프로미스 후속 처리 메서드의 콜백 함수는 **`마이크로태스크 큐(microtask queue/job queue)`** 에 저장되기 때문입니다.

마이크로태스크 큐는 태스크 큐와는 별도의 큐입니다. 마이크로태스크 큐에는 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장됩니다. 그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장됩니다.

마이크로태스크 큐는 태스크 큐보다 우선순위가 높습니다. 즉, 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행합니다. 이후 마이크로태스크 큐가 비면 태스크 큐에서 대기하고 있는 함수를 가져와 실행합니다.

<br/>

## 45.8 fetch
`fetch`함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API 입니다. **`fetch` 함수는 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭습니다.**

fetch 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달합니다.
```js
const promise = fetch(url [, option])
```

<br/>

**fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환합니다.**
```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
.then(response => console.log(response));
```
fetch 함수는 HTTP 응답을 나타내는 Response 객체는 HTTP 응답을 나타내는 다양한 프로퍼티를 제공합니다.

![image](https://github.com/SeungHyune/first-script/assets/114329713/081de6c6-0c57-4ea1-a04c-395c85a1e1b5)
Response.prototype에는 Response 객체에 포함되어 있는 HTTP 응답 몸체를 위한 다양한 메서드를 제공합니다. application/json인 HTTP 응답 몸체를 취득하려면 Response.prototype.json 메서드를 사용합니다.
Response.prototype.json 메서드는 HTTP 응답 몸체를 취득하여 역직렬화 합니다.
```js
fetch('https://jsonplaceholder.typicode.com/todos/1')
// response는 HTTP 응답을 나타내는 Response 객체입니다.
// json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화 합니다.
.then(response => response.json())
// json은 역직렬화된 HTTP 응답 몸체입니다.
.then(res => console.log(json));
// {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
```

<br/>

fetch 함수를 사용할 때는 에러 처리에 주의해야 합니다.
```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 저장되었기 때문에 404 Not Found 에러가 발생합니다.
fetch(wrongUrl)
.then(() => console.log('ok'))
.catch(() => console.log('error'));
```
부적절한 URL이 저장되었기 때문에 '404 Not Found' 에러가 발생하고 catch 메서드에 의해 'error'가 출력될 것처럼 보이지만 'ok'가 출력됩니다.

> fetch 함수가 반환하는 프로미스는 기본적으로 404 Not Found나 500 Internal Server Error와 같은 HTTP 에러가 발생해도 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve 합니다. 오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우메나 프로미스를 rejct합니다.

<br/>

따라서 fetch 함수를 사용할 때는 다음과 같이 fetch 함수가 반환한 프로미스가 resolve한 불리언 타입의 ok 상태를 확인해 명시적으로 에러를 처리할 필요가 있습니다.
```js
const wrongUrl = 'https://jsonplaceholder.typicode.com/XXX/1';

// 부적절한 URL이 저장되었기 때문에 404 Not Found 에러가 발생합니다.
fetch(wrongUrl)
// response는 HTTP 응답을 나타내는 Response 객체입니다.
.then(response => {
  if(!response.ok) throw new Error(response.statusText);
  return response.json();
})
.then(todo => console.log(todo))
.catch(err => console.log(err));
```

**참고로 `axios`는 모든 HTTP 에러를 reject하는 프로미스를 반환합니다. 모든 에러를 catch에서 처리할 수 있어 편리합니다.**

fetch 함수를 통해 HTTP 요청을 전송해보는 코드를 작성해보겠습니다.
```js
const request = {
  get(url) {
    return fetch(url);
  },
  post(url, payload) {
    return fetch(url, {
      method: 'POST',
      headers: { 'content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
  },
  patch(url, payload) {
    return fetch(url, {
      method: 'PATCH',
      headers: { 'content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
  },
  delete(url) {
    return fetch(url, {
      method: 'DELETE'
    });
  }
};
```

<br/>

### 1.GET 요청
```js
request.get('https://jsonplaceholder.typicode.com/todos/1')
.then(response => {
  if(!response.ok) throw new Error(response.statusText);
  return response.json();
})
.then(todos => console.log(todos))
.catch(err => console.log(err));
// {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
```

<br/>

### 2. POST 요청
```js
request.post('https://jsonplaceholder.typicode.com/todos', {
  userId: 1,
  title: 'JavaScript',
  completed: false
})
.then(response => {
  if(!response.ok) throw new Error(response.statusText);
  return response.json();
})
.then(todos => console.log(todos))
.catch(err => console.log(err));
// {userId: 1, title: 'JavaScript', completed: false, id: 201}
```

<br/>

### 3. PATCH 요청
```js
request.patch('https://jsonplaceholder.typicode.com/todos/1', {
  completed: true
})
.then(response => {
  if(!response.ok) throw new Error(response.statusText);
  return response.json();
})
.then(todos => console.log(todos))
.catch(err => console.log(err));
// {userId: 1, id: 1, title: 'delectus aut autem', completed: true}
```

<br/>

### 4. DELETE 요청
```js
request.delete('https://jsonplaceholder.typicode.com/todos/1')
.then(response => {
  if(!response.ok) throw new Error(response.statusText);
  return response.json();
})
.then(todos => console.log(todos))
.catch(err => console.log(err));
// {}
```